### ISSUE TITLE
BUG - get reels

### ISSUE THREAD

**Issue by damorenome** [suyashjawale/InstagramCLI#2]
when i run the code

from InstagramCLI import InstagramCLI
cli = InstagramCLI(username="XXX", password="XXX")
data= cli.get_reels(target_username="ta7oo_",save_urls=True,save_to_device=False,reel_count="all",save_music=True)
cli.close()

it shows

[19/04/2022 21:37:34] Initiating
[19/04/2022 21:37:43] Authenticating
[19/04/2022 21:37:46] Authentication Successful
[19/04/2022 21:37:46] Logging In - ETA 120 seconds
[19/04/2022 21:37:55] Login Success
[19/04/2022 21:37:55] Use save_to_device=True. As some URLs are active only for 24 hrs.
>>> data= cli.get_reels(target_username="ta7oo_",save_urls=True,save_to_device=False,reel_count="all",save_music=True)
[19/04/2022 21:38:11] Account Username : ta7oo_
[19/04/2022 21:38:13] Error occured.
Open github issue and upload error snapshot - https://github.com/suyashjawale/InstagramCLI/issues
Reason : Expecting value: line 1 column 1 (char 0)
<class 'json.decoder.JSONDecodeError'> __init__.py 201

**Comment by suyashjawale** [comment]
@damorenome  I tried above code and it works perfectly. Attaching a screenshot below. I suggest you to check if you are using 
`InstagramCLI==1.0.14` and also running the code on `windows machine` running **`python version >=3.6 and <=3.9`**.

![image](https://user-images.githubusercontent.com/58392029/164246368-bb15236c-b661-428f-a98d-b5b7509cfb6c.png)

output - 
![image](https://user-images.githubusercontent.com/58392029/164245771-e044fada-db4c-406d-8b5e-c4d131fee085.png)

Everything seems to be working correctly.
