### ISSUE TITLE
Kindly help with this issue.

### ISSUE THREAD

**Issue by Houou3** [suyashjawale/InstagramCLI#3]
> [04/06/2022 12:01:56] Initiating
[04/06/2022 12:02:16] Authenticating
[04/06/2022 12:02:19] Authentication Successful
[04/06/2022 12:02:19] Logging In - ETA 120 seconds
[04/06/2022 12:02:26] Login Success
[04/06/2022 12:02:26] Use save_to_device=True. As some URLs are active only for 24 hrs.
[04/06/2022 12:02:26] Account Username : xxxxxxxxxxx
[04/06/2022 12:02:27] Error occured.
Open github issue and upload error snapshot - https://github.com/suyashjawale/InstagramCLI/issues
Reason : Expecting value: line 1 column 1 (char 0)
<class 'json.decoder.JSONDecodeError'> __init__.py 201

**Comment by Houou3** [comment]
I have reconfirmed my python being version 3.8.8-amd64 and InstagramCLI being version 1.0.14 but the problem still persists

**Comment by suyashjawale** [comment]
Hi @Houou3 , thanks for pointing out the issue. As I checked, the API which was getting called before has now been decommissioned . Instagram uses different API for the same task now. I will update the code and publish the library soon. Will update you here when it is published.

Stay Tuned!

**Comment by suyashjawale** [comment]
Hi @Houou3 , New version of InstagramCLI has been released. Please check now. if the issue still persists. If your issue is resolved. Please close the issue.
