### ISSUE TITLE
name 'exit' is not defined

### ISSUE THREAD

**Issue by jeanneta** [suyashjawale/InstagramCLI#4]
![WhatsApp Image 2022-09-08 at 16 44 25](https://user-images.githubusercontent.com/79037720/189077750-f61060b9-ac87-4627-b029-1b6654912806.jpeg)

**Comment by suyashjawale** [comment]
Hi @jeanneta , New version of InstagramCLI has been released. Please check now. If the issue still persists, respond here. else close the issue. Thank you for your paitence
